version: '3.9'

services:
  api:
    build: ./backend/
    container_name: poll-hub-api
    ports:
      - '8000:80'
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/app:/code/app
      - ./backend/alembic:/code/alembic
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./tmp/pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
